<?xml version='1.0' encoding='UTF-8' ?>
<testsuite name="org.wikipedia.uiautomator_tests.ArticleSearchTests" tests="8" failures="2" errors="0" skipped="0" time="0.0" timestamp="2016-09-27T12:34:37" hostname="localhost">
  <properties>
    <property name="device" value="Nexus 5X - 6.0" />
    <property name="flavor" value="ALPHA" />
    <property name="project" value="app" />
  </properties>
  <testcase name="testSearchArticle_checkRecentsShown" classname="org.wikipedia.uiautomator_tests.ArticleSearchTests" time="32.071" />
  <testcase name="testSearchArticle_checkTitleShown" classname="org.wikipedia.uiautomator_tests.ArticleSearchTests" time="9.362" />
  <testcase name="testScrollingToC_clickSubHeading" classname="org.wikipedia.uiautomator_tests.ArticleTests" time="16.925" />
  <testcase name="testHistory" classname="org.wikipedia.uiautomator_tests.HistoryTests" time="37.805" />
  <testcase name="testChangeLanguageInSearch" classname="org.wikipedia.uiautomator_tests.LanguageTests" time="28.519" />
  <testcase name="testChangeLanguageInArticle" classname="org.wikipedia.uiautomator_tests.LanguageTests" time="20.635" />
  <testcase name="testAddArticleToReadingList" classname="org.wikipedia.uiautomator_tests.ReadingListTests" time="28.9">
    <failure>java.lang.AssertionError: Article: Final Fantasy XII not visible in reading list: Fancy stuff
Expected: is not null
but: was null
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.wikipedia.uiautomator_tests.ReadingListTests.testAddArticleToReadingList(ReadingListTests.java:63)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.lang.Thread.run(Thread.java:818)
</failure>
  </testcase>
  <testcase name="testOpenToC_rotatePhone" classname="org.wikipedia.uiautomator_tests.RotationTests" time="7.233">
    <failure>Test failed to run to completion. Reason: 'Test run failed to complete. Expected 9 tests, received 7'. Check device logcat for details</failure>
  </testcase>
</testsuite>